[logging]
# default = FILE:/var/log/krb5libs.log
# kdc = FILE:/var/log/krb5kdc.log
# admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = ${REALM_NAME}

[realms]
 ${REALM_NAME} = {
  kdc = kerberos.${DOMAIN}
  admin_server = kerberos.${DOMAIN}
 }

[domain_realm]
 .${DOMAIN} = ${REALM_NAME}
 ${DOMAIN} = ${REALM_NAME}
