[kerberos]
realm_name = "TESTLAB.COM"
base_dn = "dc=testlab,dc=com"
master_pass = "your-strong-master-pass!"
admin_pass = "your-strong-admin-pass!"
dm_pass = "adminpassword123!"
ticket_lifetime = "24h"
renew_lifetime = "7d"
forwardable = true
rdns = false

## Default configuration for Kerberos in LLDAP integration.
## All the values can be overridden through environment variables, prefixed
## with "LLDAP_KERB_". For instance, "realm_name" can be overridden with the
## "LLDAP_KERB_REALM_NAME" variable.
