# LLDAP + Kerberos + Keycloak federation settings
# Generated / updated via "Save Settings" button in the UI
# Password not saved here, set via env var LLDAP_KEYCLOAK_ADMIN_PASS
# Edit via "Federation" settings in UI.

url = "http://keycloak:8080"
realm = "testlab.local"
admin_user = "admin"
