//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use lldap_domain::types::{GroupId, GroupName, Uuid};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: GroupId,
    pub display_name: GroupName,
    pub lowercase_display_name: String,
    pub creation_date: chrono::NaiveDateTime,
    pub uuid: Uuid,
    pub modified_date: chrono::NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::memberships::Entity")]
    Memberships,
}

impl Related<super::memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Memberships.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for lldap_domain::types::Group {
    fn from(value: Model) -> Self {
        lldap_domain::types::Group {
            id: value.group_id,
            display_name: value.display_name,
            creation_date: value.creation_date,
            uuid: value.uuid,
            users: vec![],
            attributes: vec![],
            modified_date: value.modified_date,
        }
    }
}

impl From<Model> for lldap_domain::types::GroupDetails {
    fn from(value: Model) -> Self {
        lldap_domain::types::GroupDetails {
            group_id: value.group_id,
            display_name: value.display_name,
            creation_date: value.creation_date,
            uuid: value.uuid,
            attributes: vec![],      // populated later
            modified_date: value.modified_date,
        }
    }
}
